version: "3.9"
services:
  database:
    image: nikelin96/mcs_database:initial
  node:
    image: nikelin96/mcs_backend:initial
    # build: .
    depends_on: 
      - database
    ports:
      - "3000:3000"
    environment:
      - dbHost=database
      - host=0.0.0.0
